name: Build and push docker image

on:
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --ci --runInBand

  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: |
          IMAGE_TAG=ghcr.io/mspr-epsi-24-26/api-customers:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG ghcr.io/mspr-epsi-24-26/api-customers:latest

      - name: Push docker image
        run: |
          docker push ghcr.io/mspr-epsi-24-26/api-customers:${{ github.sha }}
          docker push ghcr.io/mspr-epsi-24-26/api-customers:latest